### ISSUE TITLE
JunkCodes

### ISSUE THREAD

**Issue by KajaKoendersNL** [jeamcsgo/jeamcheat#4]
can I add junkcodes to make it UD? 
And how to make the injector UD

**Comment by Floraly** [comment]
Junkcode: Add any code you want to cpp files. leave header files untoouched! If you added enough junk code you are fine circumvent signature checks! Build a prebuild to keep the junk code dynamic, cause you can create new junk code on compiletime! Do not use static junk code!!!

Injector: You dont need to make it undetected. gdb is not causing any VAC Ban!!! I am using GDB everyday!

**Comment by KajaKoendersNL** [comment]
@Floraly can you help me and add on discord? TRWC#5771
