### ISSUE TITLE
Credit people for pasted stuff

### ISSUE THREAD

**Issue by raspbianlike** [jeamcsgo/jeamcheat#5]
As I‘m browsing the repo a bit, I see loads of stuff that is pasted out of UC or other public sources, and you have to credit that shit as there is also something I made.. Im triggered rn

**Comment by Noriaela** [comment]
I'm gonna sue you peepee head

**Comment by LWSS** [comment]
![bazinga](https://i.imgur.com/BJGg9T1.jpg)

**Comment by jeamcsgo** [comment]
Credits to raspbianlike
